### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by bustawin** [dgilland/pydash#101]
I feel pydash is the library to do functional programming in python with more functions, and it is so sweet if you work with lodash too :-).

As a matter of efficiency when dealing with bigger data, I started to make heavy use of generators, avoiding storing intermediate big pieces of data. Unfortunately, pydash returns lists/dicts instead of generators.

By doing otherwise, we could pass that generator to another function that would query the values as needed, avoiding the cost in memory of using intermediate values –and we can always do list(my_generator).

Pydash already accept iterators as input values and you already perform lazy evaluation when chaining (although I don't know if you use internally generators for that), so some steps are already there.

A practical example would be getting data from a database and process it. In python many db libraries return a generator. This generator is passed-in in some chained methods in pydash, returning a second generator, and the second generator is passed-in to other functions that, in last instance, require the value. Computation of the value is only done in the end.

Toolz explains this [here](https://toolz.readthedocs.io/en/latest/laziness.html).

**Comment by dgilland** [comment]
I agree that a generator-first approach to pydash would be very useful (I've considered this previously). However, that's not a direction I want to take the core of pydash (i.e. that opportunity has long passed since doing it now would completely break most backwards compatibility for a large portion of the existing code base).

However, having a set of generator-based functions within pydash might be something that is doable. But these would all need to be re-implementations of the existing non-generator functions. Another possibility would be to create a separate lib that mirrors pydash but uses generators under the hood.

Did you have any other ideas on this topic?

NOTE: The lazy evaluation within chaining is more like deferred evaluation. No generators are used. Basically the composition of functions are stored and once a value is requested, values are piped through those functions but actual lists/dicts are all evaluated as if the functions were called in sequence.

**Comment by bustawin** [comment]
Unfortunately I can't think of a better way of not breaking the API (without using dirty tricks), and my hopes were with the lazy evaluation being implemented through generators.

On the other hand generators don't break much unless you are modifying lists or getting their sizes, etc. Is it the case in pydash?

**Comment by dgilland** [comment]
> On the other hand generators don't break much unless you are modifying lists or getting their sizes, etc. Is it the case in pydash?

Can you explain more about what you are asking here? I'm not quite sure I understand what exactly you're asking about.

**Comment by dgilland** [comment]
If you have other ideas, feel free to re-open.

**Comment by olirice** [comment]
Took a first swing at a (shamelessly python 3.6 only) proof-of-concept implementation with the pydash interface built on generators. Definitions for the generators were adapted from more_itertools. If this thread starts getting traction I'll add a redirect to pydash in its README. In the meantime, https://github.com/olirice/chainable
