### ISSUE TITLE
Setting an element in array by it's index will create a dict instead of an array

### ISSUE THREAD

**Issue by sebitoelcheater** [dgilland/pydash#132]
```
from pydash import py_ as _
company = {}
_.set(company, 'contacts.0.name', 'Joe')
```
will return
```
{'contacts': {'0': {'name': 'Joe'}}}
```
instead of
```
{'contacts': [{'name': 'Joe'}]}
```
as the original lodash would return.

**Comment by dgilland** [comment]
There's some ambiguity with using `".0."` since it's not clear whether that should be a list index or a dictionary key that happens to be `"0"`. For getters, pydash will try to get a list index or dictionary key, but for setter, we have to pick one or the other when there's an unset value.

Pydash uses it as a dictionary key when the value is unset so that it can handle the case where "0" is meant to be a dict key; otherwise, there would be no way to support numeric string keys. But ".0." does work for setting when the list already exists.

```python
>>> company = {'contacts': []}
>>> _.set(company, 'contacts.0.name', 'Joe')
{'contacts': [{'name': 'Joe'}]}
```

To set the initial list and to explicitly reference list indexes, the `"[N]"` pattern can be used:

```python
>>> company = {}
>>> _.set(company, 'contacts[0].name', 'Joe')
{'contacts': [{'name': 'Joe'}]}
```

**Comment by sebitoelcheater** [comment]
Thanks for your answer @dgilland. It worked.
